DSS Outcomes repository review, refactor and cleanup
SkillsFundingAgency/dss-outcomes pull request #74
Opened 2024-11-29 16:30 UTC by mimran-DFE

DSS Outcomes repository review, refactor and cleanup

2024-12-03 16:46 UTC, hnandra-DFE requested changes

2024-12-03 16:46 UTC, hnandra-DFE commented on NCS.DSS.Outcomes/Cosmos/Provider/CosmosDBProvider.cs
Requires logging similar to dss-learningprogressions: https://github.com/SkillsFundingAgency/dss-learningprogression/pull/24/files#diff-fa5bdeeb484b0b4b7e9a745b75067149baf0cff532f4ddfedd02fb09dbee1cf5

2024-12-03 16:46 UTC, hnandra-DFE commented on NCS.DSS.Outcomes/GetOutcomesByIdHttpTrigger/Function/GetOutcomesByIdHttpTrigger.cs
>              {
Need to return logging of retrieving the outcome is successful with its outcome ID

2024-12-03 16:46 UTC, hnandra-DFE commented on NCS.DSS.Outcomes/GetOutcomesHttpTrigger/Function/GetOutcomesHttpTrigger.cs
Need to return logging of retrieving the outcomes is successful with outcome IDs

2024-12-03 16:46 UTC, hnandra-DFE commented on NCS.DSS.Outcomes/PatchOutcomesHttpTrigger/Function/PatchOutcomesHttpTrigger.cs
When a 4XX response is returned, the log level should be warning for the log
When an exception is returned, the log should return the exception object and the exception message
Needs entry and exit logging on reading the request L134-L143
Needs successful and unsuccessful on the validation
Needs a log to return that the PATCH was unsuccessful

2024-12-03 16:46 UTC, hnandra-DFE commented on NCS.DSS.Outcomes/PostOutcomesHttpTrigger/Function/PostOutcomesHttpTrigger.cs
When a 4XX response is returned, the log level should be warning for the log
When an exception is returned, the log should return the exception object and the exception message
Needs a successful log when reading the request body
Needs successful and unsuccessful on the validation
The log to log success is before the service bus post so it is invalid and must be at the end of the return of the response

2024-12-03 16:46 UTC, hnandra-DFE commented
You can follow the logging I have applied in dss-learningprogressions here: https://github.com/SkillsFundingAgency/dss-learningprogression/pull/24

2024-12-17 16:25 UTC, ajones-DFE approved these changes

2024-12-17 16:36 UTC, merged